LittleKitchen/kitchen/urls.py
from django.urls import path
from . import views
app_name = 'kitchen'
urlpatterns = [
    path('',views.index_one,name='index_one'),  # 闪屏页一
    path('one/',views.index_two,name='index_two'),  # 闪屏页二

    path('login/', views.login, name='login'),  # 登录
    path('register/', views.register, name='register'),  # 注册
    path('wait/', views.wait, name='wait'),  # 等待
    path('search/', views.search, name='search'),  # 搜索
    path('fail/', views.fail, name='fail'),  # 搜索失败

    path('index/',views.index,name='index'),  # 前台首页
    path('index/s_cai/',views.s_cai,name='s_cai'),  # 去做菜
    path('index/zcend/',views.zcend,name='zcend'),  # 组菜结果
    path('index/person/',views.person,name='person'),  # 个人中心
    path('index/cpxq/<id>',views.cpxq,name='cpxq'),  # 菜谱详情
    path('index/sltj',views.sltj,name='sltj'),  # 时令推荐
    path('index/shoucang',views.shoucang,name='shoucang'),  # 用户收藏
    path('index/log_out',views.log_out,name='log_out'),  # 用户登出
    path('index/upload',views.upload,name='upload'),  # 上传图像
    path('is_login/',views.is_login,name='is_login'),  # 检测当前是否登录

    path('menu/',views.menu,name='menu'),  # 菜谱分类
    path('dealwith/',views.dealwith,name='deal_with'),  # 根据标签推荐菜谱的处理
    path('dealwithlist/<data>',views.dealwithlist,name='deal_with_list'),  # 根据标签推荐菜谱列表
    path('popular/',views.popular,name='popular'),  # 人气推荐
    path('weekpopular/',views.weekpopular,name='weekpopular'),  # 本周推荐
    path('dianzan/', views.dianzan, name='dianzan'),  # 点赞
    path('quxiao/', views.quxiao, name='quxiao'),  # 取消点赞
    path('guanzhu/', views.guanzhu, name='guanzhu'),  # 关注
    path('quguan/', views.quguan, name='quguan'),  # 取消关注

    path('index/count',views.count,name='count'),  # 评分
    path('index/season',views.season,name='season'),  # 季节

    path('find/',views.index_find,name='index_find'),#发现页
    path('DynamicDetails/<id>/',views.index_DynamicDetails,name='index_DynamicDetails'),#动态详情
    path('SubmitComments',views.SubmitComments,name='SubmitComments')#提交评论



]

LittleKitchen/little_kitchen/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('kitchen.urls')),
    path('captcha/',include('captcha.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

LittleKitchen/kitchen/models.py
from django.db import models
from db.basemodels import BaseModel
from django.contrib.auth.models import User

# Create your models here.
# 用户表
class UserInfo(BaseModel):
    name = models.OneToOneField(to=User, default="", on_delete=models.CASCADE)
    phone = models.TextField(verbose_name='手机号')
    type = models.IntegerField(verbose_name='类型',choices=(
        (0,'用户'),
        (1,'商家')
    ),default=0)
    photo = models.ImageField(verbose_name='头像',upload_to='img/',default='')
    follow = models.IntegerField(verbose_name='关注量',default=0)
    class Meta:
        verbose_name_plural = "用户表"

# 菜谱表
class Menu(models.Model):
    name = models.CharField(verbose_name='菜名',max_length=50)
    img = models.ImageField(verbose_name='图像',default='')
    ingres = models.TextField(verbose_name='食材',max_length=50)
    step = models.TextField(verbose_name='步骤',max_length=3000)
    score = models.FloatField(verbose_name='评分')
    bq = models.CharField(verbose_name='标签',max_length=50,default='')
    season = models.CharField(verbose_name='季节',max_length=11,default='')
    class Meta:
        verbose_name_plural = "菜谱表"

# 菜谱分类
class Mtype(models.Model):
    name = models.CharField(verbose_name='值', max_length=20)
    type = models.CharField(verbose_name='类型', max_length=20)
    class Meta:
        verbose_name_plural = "菜谱分类表"

# 动态表
class Dynamic(BaseModel):
    author = models.CharField(verbose_name='发布者',max_length=20)
    con = models.TextField(verbose_name='动态内容',max_length=1000)
    img = models.ImageField(verbose_name='发布图片', default='')
    z_number = models.IntegerField(verbose_name='获赞量')
    class Meta:
        verbose_name_plural = "动态管理"

# 评论表
class Comment(BaseModel):
    author = models.CharField(verbose_name='评论者',max_length=20)
    con = models.TextField(verbose_name='评论内容',max_length=1000)
    d = models.ForeignKey(verbose_name='被评论者ID',default='',to=Dynamic, on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural = "评论表"

# 用户点赞（菜谱）
class Dianzan(BaseModel):
    user = models.CharField(verbose_name='用户',max_length=200)
    c = models.ForeignKey(verbose_name='点赞对象',default='',to=Menu,on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural = "点赞"

#用户关注
class Guanzhu(BaseModel):
    user = models.CharField(verbose_name='用户',max_length=200)
    s = models.CharField(verbose_name='关注对象',default='',max_length=20)
    class Meta:
        verbose_name_plural = "关注"

# 用户收藏
class Shoucang(BaseModel):
    user = models.CharField(verbose_name='用户',max_length=200)
    c = models.ForeignKey(verbose_name='收藏菜谱',default='',to=Menu,on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural = "用户收藏"

LittleKitchen/kitchen/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse,HttpResponseRedirect,response
from .form import Login,Register,Upload
from .models import User,Menu,Mtype,Dynamic,Comment,UserInfo,Shoucang,Guanzhu,Dianzan
from django.contrib.auth import login as login1,logout
from django.views.decorators.csrf import csrf_exempt  #解决跨域
from django.db.models import Q
import random,datetime,json
# Create your views here.

##############################    韩潇 菜谱推荐    ################################
# 闪屏页一
def index_one(request):
    return render(request, 'kitchen/flash1.html')

# 闪屏页二
def index_two(request):
    return render(request, 'kitchen/flash2.html')

# 菜谱分类
def menu(request):
    data_one = Mtype.objects.filter(type='菜系').values()
    cuisine = []  # 菜系
    for item in data_one:
        cuisine.append(item['name'])
    data_two = Mtype.objects.filter(type='口味').values()
    flavor = []  # 口味
    for item in data_two:
        flavor.append(item['name'])
    data_three = Mtype.objects.filter(type='工艺').values()
    technology = []  # 工艺
    for item in data_three:
        technology.append(item['name'])
    return render(request, 'kitchen/MenuClassification.html',
                  {'technology': technology, 'cuisine': cuisine, 'flavor': flavor})


# 根据标签推荐菜谱
@csrf_exempt
def dealwith(request):
    if request.method == 'POST':
        data = request.POST.get('data')
        return redirect(reverse('kitchen:deal_with_list', kwargs={'data': data}))


def dealwithlist(request, data):
    if request.method == 'GET':
        data = data.split(',')
        menus = Menu.objects.filter(Q(bq__icontains=data[2]), Q(bq__icontains=data[1]),
                                    Q(bq__icontains=data[0])).values()
        for i in range(len(menus)):
            menus[i]['ingres'] = menus[i]['ingres'].split(',')[0]
        return render(request, 'kitchen/grouplist.html', {'menus': menus})


# 人气推荐模块
def popular(request):
    if request.method == 'GET':
        return render(request, 'kitchen/tuijian.html')


# 本周推荐列表
def weekpopular(request):
    if request.method == 'GET':
        popular = Menu.objects.all().filter(score__gt=8).values().order_by('-score')[0:20]
        for i in range(len(popular)):
            popular[i]['ingres'] = popular[i]['ingres'].split(',')[0]
        return render(request, 'kitchen/popularlist.html', {'popular': popular})


# 随机产生评分
def count(request):
    count = Menu.objects.all().count()
    for i in range(count + 1):
        num = random.uniform(4, 10)
        num = round(num, 1)
        Menu.objects.filter(id=i).update(score=num)
    return HttpResponse("成功")


# 随机产生季节
def season(request):
    count = Menu.objects.all().count()
    season_list = ['春', '夏', '秋', '冬']
    for i in range(count + 1):
        num = random.randint(0, 3)
        Menu.objects.filter(id=i).update(season=season_list[num])
    return HttpResponse("成功")

#点赞
@csrf_exempt
def dianzan(request):
    user = request.user.username
    c_id = request.POST.get('is_zan',None)
    Dianzan.objects.create(user=user,c_id=c_id)
    return HttpResponse('点赞')

#取消点赞
@csrf_exempt
def quxiao(request):
    user = request.user.username
    c_id = request.POST.get('no_zan',None)
    Dianzan.objects.filter(user=user,c_id=c_id).delete()
    return HttpResponse('取消点赞')

#关注
@csrf_exempt
def guanzhu(request):
    user = request.user.username
    s = request.POST.get('is_guan',None)
    Guanzhu.objects.create(user=user,s=s)
    return HttpResponse('关注')


#取消关注
@csrf_exempt
def quguan(request):
    user = request.user.username
    s = request.POST.get('no_guan',None)
    Guanzhu.objects.filter(user=user,s=s).delete()
    return HttpResponse('取消关注')


#######################################################################################

#############################  薛维嘉  智能组菜   ######################################

# 前台首页
def index(request):
    n_time = datetime.datetime.now()
    jijie = ''
    if n_time.month in [2, 3, 4]:
        jijie = '春'
    elif n_time.month in [5, 6, 7]:
        jijie = '夏'
    elif n_time.month in [8, 9, 10]:
        jijie = '秋'
    elif n_time.month in [11, 12, 1]:
        jijie = '冬'
    data = Menu.objects.filter(season=jijie).values()[0:3]
    popular = Menu.objects.all().filter(score__gt=8).values().order_by('-score')[0:2]
    return render(request,'kitchen/index.html',{'data':data,'popular':popular})

# 去做菜
def s_cai(request):
    if request.method == "GET":
        return render(request,'kitchen/zhinengzc.html')

# 组菜结果
def zcend(request):
    if request.method == "GET":
        return render(request,'kitchen/groupfood.html')
    else:
        shicai = request.POST.get('shicai', None)
        shicai = shicai.split(' ')
        if len(shicai) == 1:
            sc = Menu.objects.filter(Q(ingres__contains=shicai[0])).values()[0:20]
            biaoqian = {"0": shicai[0]}
            bqlen = len(biaoqian)
        elif len(shicai) == 2:
            sc = Menu.objects.filter(Q(ingres__contains=shicai[0]), Q(ingres__contains=shicai[1])).values()[0:20]
            biaoqian = {"0": shicai[0], "1": shicai[1]}
            bqlen = len(biaoqian)
        elif len(shicai) == 3:
            sc = Menu.objects.filter(Q(ingres__contains=shicai[0]), Q(ingres__contains=shicai[1]),
                                     Q(ingres__contains=shicai[2])).values()[0:20]
            biaoqian = {"0":shicai[0],"1":shicai[1],"2":shicai[2]}
            bqlen = len(biaoqian)
        return render(request, 'kitchen/groupfood.html',{'sc':sc,'biaoqian':biaoqian,'bqlen':bqlen})

# 个人中心
def person(request):
    name = request.user.username
    user = request.user.first_name
    u_id = request.user.id
    person = UserInfo.objects.filter(name_id=u_id).values().first()
    form = Upload()
    return render(request,'kitchen/person.html',{'user':user,'name':name,'person':person,'form':form})

# 菜谱详情
def cpxq(request,id):
    data = Menu.objects.filter(id=id).values('name','ingres').first()
    steps = Menu.objects.filter(id=id).values('step','score').first()
    step = steps['step']
    score = steps['score']
    name = request.user.username
    num1 = Guanzhu.objects.filter(user=name,s='食录集').first()
    if num1 == None:
        guanzhu = 0
    else:
        guanzhu = 1
    num2 = Dianzan.objects.filter(user=name,c_id=id).values().first()
    if num2 == None:
        dianzan = 0
    else:
        dianzan = 1
    return render(request,'kitchen/caipuxq.html',{'data':data,'step':step,'score':score,'id':id,'guanzhu':guanzhu,'dianzan':dianzan})



# 时令推荐
def sltj(request):
    n_time = datetime.datetime.now()
    # print(dir(n_time))
    jijie = ''
    if n_time.month in [2,3,4]:
        jijie = '春'
    elif n_time.month in [5,6,7]:
        jijie = '夏'
    elif n_time.month in [8,9,10]:
        jijie = '秋'
    elif n_time.month in [11,12,1]:
        jijie = '冬'
    data = Menu.objects.filter(season=jijie).values()[0:20]
    is_sc = Shoucang.objects.values()
    ysc = []
    for i in is_sc:
        ysc.append(i['c_id'])
    return render(request,'kitchen/season.html',{'data':data,'ysc':ysc})

# 用户收藏
@csrf_exempt
def shoucang(request):
    user = request.user.username
    c_id = request.POST.get('c_id',None)
    state = request.POST.get('state',None)
    if state == "yes":
        Shoucang.objects.create(user=user,c_id=c_id)
        return HttpResponse('已收藏')
    else:
        Shoucang.objects.filter(c_id=c_id).delete()
        return HttpResponse('收藏')

# 登出
def log_out(request):
    logout(request)
    return redirect(reverse("kitchen:login"))

#上传图片
def upload(request):
    if request.method == "POST":
        id = request.user.id
        obj = UserInfo.objects.filter(name_id=id).first()
        form = Upload(request.POST,request.FILES,instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse('kitchen:person'))
        else:
            return redirect(reverse('kitchen:person'))

#  检查当前是否登陆
def is_login(request):
    user = request.user.username
    if user == "":
        return redirect(reverse("kitchen:login"))
    else:
        return redirect(reverse("kitchen:index"))


########################################################################################


############################# 古耀华 ################################
#登录
def login(request):
    if request.method=="GET":
        form=Login()
        return render(request,"kitchen/login.html",{'form':form})
    else:
        form = Login(request.POST)
        if form .is_valid():
            print("验证成功")
            login1(request,form.user)
            return render(request, "kitchen/G_wait.html")
        else:
            form =Login()
            return redirect(reverse('kitchen:login'),{'form':form})


#注册
def register(request):
    if request.method=="POST":
        form=Register(request.POST)
        type = request.POST.get('type', None)
        if form.is_valid():
            data = form.cleaned_data
            if type == '1':
                newperson = User.objects.create_user(username=data['username'], password=data['password'],is_staff=1)
            else:
                newperson = User.objects.create_user(username=data['username'], password=data['password'])
            name_id = newperson.id
            UserInfo.objects.create(name_id=name_id, phone=newperson.username, type=type)
            return redirect("kitchen:login")
        else:
            return render(request, "kitchen/G_register.html", {'form': form})
    else:
        form=Register()
        return render(request,"kitchen/G_register.html",{'form':form})
#等待
def wait(request):
    return redirect(reverse("kitchen:index"))

#搜索菜谱失败
def fail(request):
    return redirect(reverse("kitchen:index"))
#搜索菜谱
def search(request):
    if request.method == "GET":
        pass
    else:
        dish_name=request.POST.get('dish_name',None)
        print(dish_name)
        data = Menu.objects.filter(name__icontains=dish_name).values('id').first()

LittleKitchen/kitchen/templates/kitchen/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>首页</title>
    <link rel="stylesheet" href="{% static 'kitchen/css/index.css' %}">
    <link rel="stylesheet" href="https://at.alicdn.com/t/font_996064_udode20327p.css">
    <link rel="stylesheet" href="{% static '/kitchen/swiper-4.4.6/dist/css/swiper.min.css' %}">
    <script type="text/javascript" src="{% static 'kitchen/js/rem.js' %}"></script>
</head>
<body>
    <div class="bg">
        <!-- 顶部搜索开始 -->
        <header>
            <div class="left">
                <p>太原</p>
                <span class="iconfont icon-iconfonticonfonti2"></span>
            </div>
            <form action="/search/" method="post" style="display:flex;">
                {% csrf_token %}
                <div class="min">
                    <input type="text" name="dish_name" id="" placeholder="请输入您要搜索菜名">
                    <img src="{% static 'kitchen/img/index2_l.gif' %}" alt="">
                </div>
                <button class="right" type="submit">
                    <img src="{% static 'kitchen/img/index1_l.gif' %}" alt="">
                </button>
            </form>
        </header>
        <!-- 顶部搜索结束 -->
        <!-- 轮播图开始 -->
        <div class="swiper-container" id="lunbo">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <img src="{% static 'kitchen/img/lunbo1_l.png' %}" alt="" class="img">
                    <div class="text">
                        <img src="{% static 'kitchen/img/lbtext1_l.png' %}" alt="" class="text1">
                        <img src="{% static 'kitchen/img/lbtext2_l.png' %}" alt="" class="text2">
                        <img src="{% static 'kitchen/img/lbtext3_l.png' %}" alt="" class="text3">
                    </div>
                </div>
                <div class="swiper-slide"><img src="{% static 'kitchen/img/lunbo2_l.png' %}" alt="" class="img"></div>
                <div class="swiper-slide"><img src="{% static 'kitchen/img/lunbo3_l.png' %}" alt="" class="img"></div>
            </div>
            <!-- 如果需要分页器 -->
            <div class="swiper-pagination"></div>
        </div>
        <!-- 轮播图结束 -->
        <!-- 选择按钮开始 -->
        <section class="change">
            <div class="box">
                <button class="aptitude">
                    <a href="{% url 'kitchen:s_cai' %}">
                        <img src="{% static 'kitchen/img/change2_l.gif' %}" alt="">
                        <span>智能组菜</span>
                    </a>
                </button>
                <button class="menu">
                    <a href="{% url 'kitchen:menu' %}">
                        <img src="{% static 'kitchen/img/change1_l.png' %}" alt="">
                        <span>菜谱分类</span>
                    </a>
                </button>
            </div>
        </section>
        <!-- 选择按钮结束 -->
        <!-- 时令推荐开始 -->
        <section class="season">
            <div class="top">
                <h2>时令推荐</h2>
                <a href="{% url 'kitchen:sltj' %}">
                    <p>查看全部 <span class="iconfont icon-iconfonticonfonti2copycopy"></span> </p>
                </a>
            </div>
            <div class="main">
                <ul>
                    {% for item in data %}
                    <li>
                        <a href="/index/cpxq/{{ item.id }}">
                            <img src="{{ item.img }}" alt="" class="food">
                            <h2>{{ item.name }}</h2>
                            <p> <span>评分星级：</span></p>
                            <div class="stars">
                                {% if item.score > 6 and item.score < 9 %}
                                <img src="{% static 'kitchen/image/lxing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/lxing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/axing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                {% elif item.score > 3 and item.score < 6 %}
                                <img src="{% static 'kitchen/image/lxing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/axing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/axing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                {% elif item.score > 9 %}
                                <img src="{% static 'kitchen/image/lxing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/lxing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/lxing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                {% else %}
                                <img src="{% static 'kitchen/image/axing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/axing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/axing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                {% endif %}
                            </div>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </section>
        <!-- 时令推荐结束 -->
       
        <!-- 人气推荐开始 -->
        <section class="popularity">
            <div class="top">
                <h2>人气推荐</h2>
                <a href="{% url 'kitchen:popular' %}">
                    <p>查看全部 <span class="iconfont icon-iconfonticonfonti2copycopy"></span> </p>
                </a>
            </div>
            <div class="main">
                <ul>
                    {% for item in popular %}
                    <li>
                        <a href="/index/cpxq/{{ item.id }}">
                            <div class="img">
                                <img style="margin-left:0.65rem;" src="{{ item.img }}" alt="" class="pfood">
                            </div>
                            <p>养生菌菇锅</p>
                            <span>选自健康食材，精心烹制</span>
                            <div class="stars">
                                {% if item.score > 6 and item.score < 9 %}
                                <img src="{% static 'kitchen/image/lxing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/lxing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/axing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                {% elif item.score > 3 and item.score < 6 %}
                                <img src="{% static 'kitchen/image/lxing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/axing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/axing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                {% elif item.score > 9 %}
                                <img src="{% static 'kitchen/image/lxing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/lxing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/lxing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                {% else %}
                                <img src="{% static 'kitchen/image/axing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/axing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                <img src="{% static 'kitchen/image/axing.png' %}" alt="" style="display:block;width:0.23rem;height:0.32rem;margin:0;">
                                {% endif %}
                            </div>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </section>
        <!-- 人气推荐结束 -->
        <!-- 底部开始 -->
        <footer>
            <div class="box">
                <a href="javascript:;" class="home">
                    <img src="{% static 'kitchen/img/home1_l.png' %}" alt="">
                    <span style="color: #FDBB33;">首页</span>
                </a>
                <a href="{% url 'kitchen:index_find' %}" class="home">
                    <img src="{% static 'kitchen/img/find1_l.png' %}" alt="">
                    <span>发现</span>
                </a>
                <a href="" class="home">
                    <img src="{% static 'kitchen/img/shop1_l.png' %}" alt="">
                    <span>商城</span>
                </a>
                <a href="{% url 'kitchen:person' %}" class="home">
                    <img src="{% static 'kitchen/img/my1_l.png' %}" alt="">
                    <span>我的</span>
                </a>
            </div>
        </footer>
        <!-- 底部结束 -->
    </div>
    <script src="{% static 'kitchen/swiper-4.4.6/dist/js/swiper.min.js' %}"></script>
    <script>        
        var mySwiper = new Swiper ('.swiper-container', {
          autoplay: true,//可选选项，自动滑动
          loop: true, // 循环模式选项
          // 如果需要分页器
          pagination: {
            el: '.swiper-pagination',
          },
        })        
        </script>
</body>
</html>

LittleKitchen/kitchen/templates/kitchen/zhinengzc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>智能组菜</title>
    <link rel="stylesheet" href="{% static 'kitchen/css/zhinengzc.css' %}">
    <link rel="stylesheet" href="https://at.alicdn.com/t/font_996064_je37tojj2n.css">
    <link rel="stylesheet" href="{% static 'kitchen/swiper-4.4.6/dist/css/swiper.min.css' %}">
    <script type="text/javascript" src="{% static 'kitchen/js/rem.js' %}"></script>
</head>
<body>
    <!-- 头部开始 -->
    <header>
        <div class="title">
            <a href="{% url 'kitchen:index' %}" class="tleft">
                <i class="iconfont icon-jiantouarrowhead7"></i>
            </a>
            <h2 class="tright">
                智能组菜
            </h2>
        </div>
    </header>
    <!-- 头部结束 -->
    <div class="bg">
        <form method="post" action="{% url 'kitchen:zcend' %}">
            {% csrf_token %}
            <div class="ssou">
                <input type="text" name="shicai" id="sc" placeholder="请输入食材 将食材用 空格 隔开">
                <span class="iconfont icon-sousuo"></span>
            </div>
            <button type="submit" class="anniu" >去组菜</button>
        </form>
    </div>
    
</body>
</html>